name: Box16 Build CI
on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencnies
        run: |
          sudo apt-get install -y make build-essential libglew-dev libgtk-3-dev libsdl2-dev libsdl2-image-dev
      - name: Build Box16 (Ubuntu)
        run: |
          cd build
          make
      - name: Archive Ubuntu build
        uses: actions/upload-artifact@v3
        with:
          name: Box16 (Ubuntu)
          path: build/box16/
  build-win32-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      - name: Build Box16 (Win32 Debug)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Debug
          cd ..
          mkdir -p box16-Win32-Debug
          cp vs2022/out/Win32/Debug/Box16.exe box16-Win32-Debug/
          cp vs2022/out/Win32/Debug/glew32.dll box16-Win32-Debug/
          cp vs2022/out/Win32/Debug/SDL2.dll box16-Win32-Debug/
          cp vs2022/out/Win32/Debug/box16-icon56-24.png box16-Win32-Debug/
          cp vs2022/out/Win32/Debug/icons.png box16-Win32-Debug/
          cp vs2022/out/Win32/Debug/README.box16 box16-Win32-Debug/
      - name: Archive Win32-Debug build
        uses: actions/upload-artifact@v3
        with:
          name: Box16 (Win32 Debug)
          path: build/box16-Win32-Debug/
  build-win32-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      - name: Build Box16 (Win32 Release)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
          cd ..
          mkdir -p box16-Win32-Release
          cp vs2022/out/Win32/Release/Box16.exe box16-Win32-Release/
          cp vs2022/out/Win32/Release/glew32.dll box16-Win32-Release/
          cp vs2022/out/Win32/Release/SDL2.dll box16-Win32-Release/
          cp vs2022/out/Win32/Release/box16-icon56-24.png box16-Win32-Release/
          cp vs2022/out/Win32/Release/icons.png box16-Win32-Release/
          cp vs2022/out/Win32/Release/README.box16 box16-Win32-Release/
      - name: Archive Win32-Release build
        uses: actions/upload-artifact@v3
        with:
          name: Box16 (Win32 Release)
          path: build/box16-Win32-Release/
  build-win64-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build Box16 (x64 Debug)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Debug
          cd ..
          mkdir -p box16-x64-Debug
          cp vs2022/out/x64/Debug/Box16.exe box16-x64-Debug/
          cp vs2022/out/x64/Debug/glew32.dll box16-x64-Debug/
          cp vs2022/out/x64/Debug/SDL2.dll box16-x64-Debug/
          cp vs2022/out/x64/Debug/box16-icon56-24.png box16-x64-Debug/
          cp vs2022/out/x64/Debug/icons.png box16-x64-Debug/
          cp vs2022/out/x64/Debug/README.box16 box16-x64-Debug/
      - name: Archive x64-Debug build
        uses: actions/upload-artifact@v3
        with:
          name: Box16 (x64 Debug)
          path: build/box16-x64-Debug/
  build-win64-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build Box16 (x64 Release)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
          cd ..
          mkdir -p box16-x64-Release
          cp vs2022/out/x64/Release/Box16.exe box16-x64-Release/
          cp vs2022/out/x64/Release/glew32.dll box16-x64-Release/
          cp vs2022/out/x64/Release/SDL2.dll box16-x64-Release/
          cp vs2022/out/x64/Release/box16-icon56-24.png box16-x64-Release/
          cp vs2022/out/x64/Release/icons.png box16-x64-Release/
          cp vs2022/out/x64/Release/README.box16 box16-x64-Release/
      - name: Archive x64-Release build
        uses: actions/upload-artifact@v3
        with:
          name: Box16 (x64 Release)
          path: build/box16-x64-Release/

